version: '3'
services:
    webapi:
        build:
            context: avion-api
            dockerfile: Dockerfile
        volumes:
            - ./avion-api/api:/app/api
            - ./avion-api/domain:/app/domain
            - ./avion-api/flyway:/flyway
            - ./local/db:/db
            - ./local/avion.conf:/etc/avion.conf
        ports:
            - "5000:5000"
        environment:
            - AVION_CONFIG=/etc/avion.conf
        restart: "unless-stopped"
